name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd shibadev
            git pull
            docker kill $(docker ps -q)
            docker rmi shibadev-client
            docker rmi shibadev-server
            cd client
            docker build -t shibadev-client .
            cd ../server
            docker build -t shibadev-server .
            docker rm -f shibadev-client shibadev-server
            docker run -dp 8000:8000 --name shibadev-server shibadev-server
            docker run -dp 3000:3000 --name shibadev-client shibadev-client
            echo 'Deployment successful to server using docker'
